# Site settings
title: Jordan Drake
email: jordan@jdrake.co.uk
description: "This is a work in progress!"
baseurl: ""
url: "http://jordrake.github.io"
twitter_username: jordrake
github_username:  jordrake

# Build settings
markdown: kramdown
permalink: pretty
