# Site settings
title: Jordan Drake
email: jordan@jdrake.co.uk
description: "This is a work in progress!"
baseurl: ""
url: "http://jordrake.github.io"
twitter_username: jordrake
github_username:  jordrake
linkedin_url: "http://uk.linkedin.com/in/jordrake"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5
paginate_path: "/page/:num"
